name: Dev branch build
trigger:
- dev

pool:
  vm-image: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'
- script: pip install -r requirements.txt
  displayName: 'Installing requirements'
- script: ls -l
  displayName: 'Checksck directory'
- script: 'pytest --junitxml=reports/gitops.xml'
  displayName: 'Running tests'
- script: 'ls -l'
  displayName: List files
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'reports/gitops.xml'
    testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)] - Python $(python.version)'
  condition: succeededOrFailed()
