name: Dev branch build
trigger:
- dev

pool:
  vm-image: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'
- script: pip install -r requirements.txt
  displayName: 'Installing requirements'
- script: ls -l
  displayName: 'Check directory'
#- script: 'pytest --junitxlm=../../reports/gitops.xml'
#  displayName: 'Running tests'